# Generated by Django 3.0.7 on 2020-06-16 04:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salesmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%M/%d/')),
                ('photo_1', models.ImageField(
                    blank=True, upload_to='photos/%Y/%M/%d/')),
                ('photo_2', models.ImageField(
                    blank=True, upload_to='photos/%Y/%M/%d/')),
                ('photo_3', models.ImageField(
                    blank=True, upload_to='photos/%Y/%M/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(
                    blank=True, default=datetime.datetime.now)),
                ('salesmanager', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='salesmanager.Salesmanager')),
            ],
        ),
    ]
